[package]
name = "fflo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
libm = "*"
image = "*"
minifb = "*"
rusttype = "*"
imageproc = "*"
float_extras = "*"

